trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

# Stage 1
# Build Docker Image
# Publish the K8S Files
stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'nodejs-microservices-docker-hub'
            repository: 'msinfoorigin/nodejs-microservices-devops'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(tag)'
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/*.yaml'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'manifests'
            publishLocation: 'Container'
  - stage: Deploy
    displayName: Deploy image
    jobs:
    - job: Deploy
      displayName: Deploy
      pool:
        vmImage: "ubuntu-latest"
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'manifests'
          itemPattern: '**/*.yaml'
          targetPath: '$(System.ArtifactsDirectory)'
      - task: KubernetesManifest@0
        inputs:
          action: 'bake'
          namespace: 'default'
          containers: 'msinfoorigin/nodejs-microservices-devops:$(tag)'
          helmChart: 'charts/sample'
# Stage 2
# Download the K8S Files
# Deploy to K8S Cluster with Docker Image
