trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@0
  inputs:
    command: 'forceunlock'
    allowTelemetryCollection: true
    lockID: 'a8a4058c-7c0a-4343-be72-f6661d8a123b'