trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@0
  inputs:
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    environmentServiceName: 'az-rm-sc'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publicKey.secureFilePath)'
    allowTelemetryCollection: true
